humanoid_shp:
  # Position Controllers ---------------------------------------
  joint_chest_position_controller:
    type: position_controllers/JointPositionController
    joint: chest
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Lankle_position_controller:
    type: position_controllers/JointPositionController
    joint: left_ankle
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Lelbow_position_controller:
    type: position_controllers/JointPositionController
    joint: left_elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Lhip_position_controller:
    type: position_controllers/JointPositionController
    joint: left_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Lknee_position_controller:
    type: position_controllers/JointPositionController
    joint: left_knee
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Lshoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: left_shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_neck_position_controller:
    type: position_controllers/JointPositionController
    joint: neck
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Rankle_position_controller:
    type: position_controllers/JointPositionController
    joint: right_ankle
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Relbow_position_controller:
    type: position_controllers/JointPositionController
    joint: right_elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Rhip_position_controller:
    type: position_controllers/JointPositionController
    joint: right_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Rknee_position_controller:
    type: position_controllers/JointPositionController
    joint: right_knee
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_Rshoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: right_shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}

 

 
